# Generated by Django 4.0.3 on 2022-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=50)),
                ('salario', models.FloatField(null=True)),
                ('local', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('contato', models.EmailField(max_length=254, null=True)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'Empregado registrado pela CLT'), ('PJ', 'Pessoa jurídica')], max_length=3)),
                ('tecnologias', models.ManyToManyField(to='api.tecnologia')),
            ],
        ),
    ]
